import json
from pathlib import Path
from openpyxl import Workbook

from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

import matplotlib.pyplot as plt

REPORT_DIR = "/var/jenkins_home/reports/raw"

files = [
    "trivy-fs.json",
    "trivy-image.json"
]

summary = {
    "CRITICAL": 0,
    "HIGH": 0,
    "MEDIUM": 0,
    "LOW": 0
}

summary_json = {
    "critical": 0,
    "high": 0,
    "medium": 0,
    "low": 0
}

# Parse Trivy reports
for report in files:
    path = f"{REPORT_DIR}/{report}"

    try:
        with open(path, "r") as f:
            data = json.load(f)

        for result in data.get("Results", []):
            for vuln in result.get("Vulnerabilities", []):
                sev = vuln.get("Severity", "").upper()

                if sev in summary:
                    summary[sev] += 1

    except Exception as e:
        print(f"Error reading {report}: {e}")

# Build JSON summary
summary_json["critical"] = summary["CRITICAL"]
summary_json["high"] = summary["HIGH"]
summary_json["medium"] = summary["MEDIUM"]
summary_json["low"] = summary["LOW"]

# Create output directory
Path("/var/jenkins_home/reports/final").mkdir(
    parents=True,
    exist_ok=True
)

# ------------------------------------------------------------------
# JSON REPORT
# ------------------------------------------------------------------

json_output = "/var/jenkins_home/reports/final/security-summary.json"

with open(json_output, "w") as f:
    json.dump(summary_json, f, indent=4)

print("JSON Summary generated:")
print(json_output)

# ------------------------------------------------------------------
# EXCEL REPORT
# ------------------------------------------------------------------

wb = Workbook()

ws = wb.active
ws.title = "Security Summary"

ws.append(["Severity", "Count"])

ws.append(["CRITICAL", summary["CRITICAL"]])
ws.append(["HIGH", summary["HIGH"]])
ws.append(["MEDIUM", summary["MEDIUM"]])
ws.append(["LOW", summary["LOW"]])

excel_output = "/var/jenkins_home/reports/final/security-report.xlsx"

wb.save(excel_output)

print("Excel Report generated:")
print(excel_output)

# ------------------------------------------------------------------
# PDF REPORT
# ------------------------------------------------------------------

pdf_output = "/var/jenkins_home/reports/final/security-report.pdf"

doc = SimpleDocTemplate(pdf_output)

styles = getSampleStyleSheet()

elements = []

title = Paragraph(
    "DevSecOps Security Report",
    styles["Title"]
)

elements.append(title)
elements.append(Spacer(1, 12))

generated_by = Paragraph(
    "Generated By: DevSecOps Aggregator",
    styles["Normal"]
)

elements.append(generated_by)
elements.append(Spacer(1, 12))

source_reports = Paragraph(
    """
    Source Reports:<br/>
    - Trivy Filesystem Scan<br/>
    - Trivy Image Scan
    """,
    styles["Normal"]
)

elements.append(source_reports)
elements.append(Spacer(1, 20))

table_data = [
    ["Severity", "Count"],
    ["CRITICAL", summary["CRITICAL"]],
    ["HIGH", summary["HIGH"]],
    ["MEDIUM", summary["MEDIUM"]],
    ["LOW", summary["LOW"]]
]

table = Table(table_data)

table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")
    ])
)

elements.append(table)

doc.build(elements)

print("PDF Report generated:")
print(pdf_output)

# ------------------------------------------------------------------
# CHART REPORT
# ------------------------------------------------------------------

labels = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]

values = [
    summary["CRITICAL"],
    summary["HIGH"],
    summary["MEDIUM"],
    summary["LOW"]
]

plt.figure(figsize=(8, 5))

plt.bar(labels, values)

plt.title("Security Vulnerability Distribution")

plt.xlabel("Severity")
plt.ylabel("Count")

chart_output = "/var/jenkins_home/reports/final/security-chart.png"

plt.savefig(chart_output)

plt.close()

print("Chart generated:")
print(chart_output)

# ------------------------------------------------------------------
# HTML REPORT
# ------------------------------------------------------------------

html = f"""
<html>
<head>
<title>DevSecOps Security Report</title>
</head>
<body>

<h1>Security Summary</h1>

<p><b>Generated By:</b> DevSecOps Aggregator</p>

<p>
<b>Source Reports:</b><br>
- Trivy Filesystem Scan<br>
- Trivy Image Scan
</p>

<table border="1" cellpadding="5" cellspacing="0">
<tr>
<th>Severity</th>
<th>Count</th>
</tr>

<tr><td>CRITICAL</td><td>{summary['CRITICAL']}</td></tr>
<tr><td>HIGH</td><td>{summary['HIGH']}</td></tr>
<tr><td>MEDIUM</td><td>{summary['MEDIUM']}</td></tr>
<tr><td>LOW</td><td>{summary['LOW']}</td></tr>

</table>

</body>
</html>
"""

html_output = "/var/jenkins_home/reports/final/security-report.html"

with open(html_output, "w") as f:
    f.write(html)

print("HTML Report generated:")
print(html_output)
